# Generated by Django 2.2.7 on 2020-02-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='way',
            field=models.CharField(default=0, max_length=600),
            preserve_default=False,
        ),
    ]
