# Generated by Django 2.2.7 on 2020-02-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200215_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='letter',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
